name: Frontend CI/CD to S3

on:
  push:
    branches:
      - main # This workflow runs when a push is made to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use the version of Node.js your project needs

      - name: Install dependencies
        run: npm install

      - name: Create .env file from secrets
        run: |
          echo "REACT_APP_COGNITO_REGION=${{ secrets.REACT_APP_COGNITO_REGION }}" >> .env
          echo "REACT_APP_COGNITO_USER_POOL_ID=${{ secrets.REACT_APP_COGNITO_USER_POOL_ID }}" >> .env
          echo "REACT_APP_COGNITO_CLIENT_ID=${{ secrets.REACT_APP_COGNITO_CLIENT_ID }}" >> .env
        shell: bash

      - name: Build frontend
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://karina-winter --delete